#pragma once

#include <SFML/Graphics.hpp>
#include <iostream>
#include <vector>
#include <cmath>
#include <cstring>
#include <ctime>
#include <cstdlib>
#include "ball.hpp"

constexpr int WINDOW_WIDTH = 800;
constexpr int WINDOW_HEIGHT = 600;
constexpr int COLOR_NUM = 7; // number of colors for balls
constexpr int BALL_BOUND = 50; // max number of ball that can spawn
constexpr float BALL_RADIUS = 10.0f; // radius of each all ball in the bigger ball

constexpr float CELL_SIZE = 80.0f;  // Should be > 2*ball_radius
constexpr int GRID_WIDTH = static_cast<int>(WINDOW_WIDTH / CELL_SIZE) + 1;
constexpr int GRID_HEIGHT = static_cast<int>(WINDOW_HEIGHT / CELL_SIZE) + 1;

float mySqrt(float x, float y) { // This function has been generated by AI for faster computation
    
    float sq = x*x + y*y;
    
    // Handle special cases: zero, negative, or very small values
    if (sq <= 0.0f) return 0.0f;
    
    float xhalf = 0.5f * sq;
    int i;
    std::memcpy(&i, &sq, sizeof(int));
    
    // Magic constant for initial approximation
    i = 0x5F3759DF - (i >> 1);
    
    float y_approx;
    std::memcpy(&y_approx, &i, sizeof(float));
    
    // First Newton-Raphson iteration
    y_approx = y_approx * (1.5f - xhalf * y_approx * y_approx);
    // Second Newton-Raphson iteration for improved accuracy
    y_approx = y_approx * (1.5f - xhalf * y_approx * y_approx);
    
    return sq * y_approx;
}